language: node_js
node_js: 
  - '7'
  - 'stable'
cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@latest yarn@latest
install:
  - npm install
script:
  - npm run test
after_script:
  - npm run cover